# -*- coding: utf-8 -*-
"""Road Accident Severity.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DmFCwGV_I8_-cn_ztYWyRlDo02QVo4O5
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_selection import SelectKBest
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder
from sklearn.feature_selection import chi2
from sklearn.feature_selection import mutual_info_classif
from sklearn.decomposition import PCA
from imblearn.over_sampling import SMOTENC
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import confusion_matrix, classification_report, f1_score
import joblib
from PIL import Image
import PIL

# %matplotlib inline

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

df = pd.read_csv('/content/RTA Dataset.csv')

df.head()

df.shape

df.info()

df.isnull().sum()

# target variable classes counts and bar plot
print(df['Accident_severity'].value_counts())
df['Accident_severity'].value_counts().plot(kind='bar')

#Education lavel of drivers
df['Educational_level'].value_counts().plot(kind='bar')

# plot a point plot for categorical features and target variable
plt.figure(figsize=(6,5))
sns.catplot(x='Educational_level', y='Accident_severity', data=df)
plt.xlabel("Educational level")
plt.xticks(rotation=60)
plt.show()

#Visualizing datasets using dabl(data analysis baseline library)
!pip install dabl

import dabl

"""#dabl data analysis"""

dabl.plot(df, target_col='Accident_severity')

df.corr()

"""# Some Insights from the Initial Data Analysis:

More the Number of casualties, higher the chances of fatal injuries at accident site

More the vehicles involved higher the chances of Serious injury

Light_conditions being darkness can cause higher serious injury

data is highly imbalanced

Features like (area_accident_occured, Cause_of_accident, Day_of_week, 

type_of_junction) seem to be imporatant features causing fatal injuries

Road_surface and road conditions do not affect fatal or serious accidents apparently

# plot the bar plot of road_surface_type and accident severity feature
"""

print(df['Road_surface_type'].value_counts())
plt.figure(figsize=(6,5))
sns.countplot(x='Road_surface_type', hue='Accident_severity', data=df)
plt.xlabel('Rode surafce type')
plt.xticks(rotation=60)
plt.show

print(df['Road_surface_conditions'].value_counts())

plt.figure(figsize=(6,5))
sns.countplot(x='Road_surface_conditions', hue='Accident_severity', data=df)
plt.xlabel('Rode condition type')
plt.xticks(rotation=60)
plt.show

"""# **How does road_surface affact injuries?**"""

pivot_df = pd.pivot_table(data=df,index='Road_surface_conditions',columns='Accident_severity',aggfunc='count')

fatal_df = pivot_df['Road_surface_type']
fatal_df.fillna(0, inplace=True)
fatal_df['sum_of_injuries'] = fatal_df['Fatal injury'] + fatal_df['Serious Injury'] + fatal_df['Slight Injury']
fatal_df

fatal_df_dry = (fatal_df.loc['Dry']/fatal_df.loc['Dry','sum_of_injuries'])*100
fatal_df_dry

fatal_df_snow = (fatal_df.loc['Wet or damp']/fatal_df.loc['Wet or damp','sum_of_injuries'])*100
fatal_df_snow

df.groupby('Road_surface_conditions')['Accident_severity'].count()

"""# Converting object type column to DateTime Datatype column"""

df['Time'] = pd.to_datetime(df['Time'])

obj_cols = [col for col in df.columns if df[col].dtypes == 'object']
obj_cols2 = [col for col in obj_cols if col != 'Accident_severity']
obj_cols2

"""Data Pre-Processing

# Extrating 'Hour_of_Day' feature from the time feature
"""

# remove time column from datafram
new_df = df.copy()
new_df['Hour_of_Day'] = new_df['Time'].dt.hour
n_df = new_df.drop('Time', axis=1)
n_df

"""# categorical data visualization"""

# data visualizationf of categorical cols

def count_plot(col):
    n_df[col].value_counts()
    
    # plot the figure of count plot
    plt.figure(figsize=(5,5))
    sns.countplot(x=col, hue='Accident_severity', data=n_df)
    plt.xlabel(f'{col}')
    plt.xticks(rotation=60)
    plt.show
    
for col in obj_cols:
    count_plot(col)

# disribution of hour of the day
plt.figure(figsize=(5,5))
sns.displot(x='Hour_of_Day', hue='Accident_severity', data=n_df)
plt.show()

"""# Data pre-processing"""

# feature selection based on visualization (to_be_continue)
features = ['Day_of_week','Number_of_vehicles_involved','Number_of_casualties','Area_accident_occured',
           'Types_of_Junction','Age_band_of_driver','Sex_of_driver','Educational_level',
           'Vehicle_driver_relation','Type_of_vehicle','Driving_experience','Service_year_of_vehicle','Type_of_collision',
           'Sex_of_casualty','Age_band_of_casualty','Cause_of_accident','Hour_of_Day']
len(features)

# new dataframe generated
featureset_df = n_df[features]
target = n_df['Accident_severity']

# meta data of the new sub dataset
featureset_df.info()

"""#Missing value treatment"""

feature_df = featureset_df.copy()

"""Missing value approch


*   Most the missing values in features could be result of non-availability during investigation of the accident site, hence we will replace it as a 'Unknown' in all the columns in this case.


"""

# NaN are missing because service info might not be available, we will fill as 'Unknowns'
feature_df['Service_year_of_vehicle'] = feature_df['Service_year_of_vehicle'].fillna('Unknown')
feature_df['Types_of_Junction'] = feature_df['Types_of_Junction'].fillna('Unknown')
feature_df['Area_accident_occured'] = feature_df['Area_accident_occured'].fillna('Unknown')
feature_df['Driving_experience'] = feature_df['Driving_experience'].fillna('unknown')
feature_df['Type_of_vehicle'] = feature_df['Type_of_vehicle'].fillna('Other')
feature_df['Vehicle_driver_relation'] = feature_df['Vehicle_driver_relation'].fillna('Unknown')
feature_df['Educational_level'] = feature_df['Educational_level'].fillna('Unknown')
feature_df['Type_of_collision'] = feature_df['Type_of_collision'].fillna('Unknown')

feature_df.info()

"""#One Hot Encoding

One-hot encoding to encode categorical features and LabelEncoder() to encode the labels
"""

X = feature_df[features]
y = target

# we will use pandas get_dummies method for on-hot encoding
encoded_df = pd.get_dummies(X, drop_first=True)
encoded_df.shape

"""#Lable encoding of Target Feature"""

lb = LabelEncoder()
lb.fit(y)
y_encoded = lb.transform(y)
print("Encoded labels:",lb.classes_)
y_en = pd.Series(y_encoded)

"""# 1: serious injury, 2: Slight injury, 0: Fatal Injury

#Feature selection using k best chi2 method
"""

## mutual info classif to check informative features
mi_calc = mutual_info_classif(encoded_df, y_en, random_state=42)

mi_df = pd.DataFrame({'Columns':encoded_df.columns, 'MI_score':mi_calc})
mi_df.sort_values(by='MI_score',ascending=False).head(15)

# feature seleciton method using chi2 for categorical output, categorical input
fs = SelectKBest(chi2, k=50)
X_new = fs.fit_transform(encoded_df, y_en)
X_new.shape
cols = fs.get_feature_names_out()

fs_df = pd.DataFrame(X_new, columns=cols)

"""#PCA"""

pca = PCA(n_components=3)
pca.fit(encoded_df)

X_pca = pca.transform(encoded_df)

# 3 components PCA algorithm
components = pca.components_

pca_df = pd.DataFrame(X_pca, columns={'PC1','PC2','PC3'})
pca_df.var()

"""#Imbalance data treatment"""

# categorical features for SMOTENC technique for categorical features
n_cat_index = np.array(range(3,50))

smote = SMOTENC(categorical_features=n_cat_index, random_state=42, n_jobs=True)
X_n, y_n = smote.fit_resample(fs_df,y_en)
X_n.shape, y_n.shape

y_n.value_counts()

"""#Modelling baseline and hyper parameter tuning"""

# train and test split and building baseline model to predict target features
X_trn, X_tst, y_trn, y_tst = train_test_split(X_n, y_n, test_size=0.2, random_state=42)

# modelling using random forest baseline
rf = RandomForestClassifier(n_estimators=800, max_depth=20, random_state=42)
rf.fit(X_trn, y_trn)
# predicting on test data
predics = rf.predict(X_tst)

# train score 
rf.score(X_trn, y_trn)

classif_re = classification_report(y_tst,predics)
print(classif_re)

conf_matrix = confusion_matrix(y_tst, predics)
conf_matrix

f1score = f1_score(y_tst,predics, average='weighted')
print(f1score)

"""#Modeling for deployment on streamlit cloud"""

# encoder categorical features
cat_fea_df = feature_df.drop(['Hour_of_Day','Number_of_vehicles_involved','Number_of_casualties'], axis=1)

oencoder = OrdinalEncoder()
encoded_df2 = pd.DataFrame(oencoder.fit_transform(cat_fea_df))
encoded_df2.columns = cat_fea_df.columns

new_fea_df = feature_df[['Type_of_collision','Age_band_of_driver','Sex_of_driver',
       'Educational_level','Service_year_of_vehicle','Day_of_week','Area_accident_occured']]

oencoder2 = OrdinalEncoder()
encoded_df3 = pd.DataFrame(oencoder2.fit_transform(new_fea_df))
encoded_df3.columns = new_fea_df.columns

oencoder2.transform(new_fea_df.iloc[0:1,:]).reshape(1,-1)
#np.array(new_fea_df.iloc[0,:],ndmin=2)

# save the encoder
joblib.dump(oencoder, "ordinal_encoder.joblib")

joblib.dump(oencoder2, "ordinal_encoder2.joblib")

final_df = pd.concat([encoded_df2,feature_df[['Hour_of_Day','Number_of_vehicles_involved','Number_of_casualties']]], axis=1)
final_df.head()

## mutual info classif to check informative features
mi_calc2 = mutual_info_classif(final_df, y_en, random_state=42)
mi_df2 = pd.DataFrame({'Columns':final_df.columns, 'MI_score':mi_calc2})
mi_df2_sorted = mi_df2.sort_values(by='MI_score',ascending=False)
mi_df2_sorted

# we will remove features with mi_Score of zero and keep only first top10 most significant features
cols_list = list(mi_df2_sorted['Columns'][:10])
final_df2 = final_df[cols_list]

s_final_df = pd.concat([feature_df[['Number_of_vehicles_involved','Number_of_casualties','Hour_of_Day']],encoded_df3], axis=1)
s_final_df.head()

# train and test split and building baseline model to predict target features
X_trn2, X_tst2, y_trn2, y_tst2 = train_test_split(s_final_df, y_en, test_size=0.2, random_state=42)

# modelling using random forest baseline
rf = RandomForestClassifier(n_estimators=700, max_depth=20, random_state=42)
rf.fit(X_trn2, y_trn2)
# predicting on test data
predics2 = rf.predict(X_tst2)

X_trn2.info()

newd = X_tst2.sample(10)
sampl_arr = np.array(newd.iloc[0]).reshape(1,-1)
sampl_arr

!pip install shap

import shap

shap.initjs()
shap_values = shap.TreeExplainer(rf).shap_values(sampl_arr)
shap.force_plot(shap.TreeExplainer(rf).expected_value[0], shap_values[0], sampl_arr, matplotlib=True,show=False)
plt.savefig("pred_force_plot1.png")

img = Image.open("/content/pred_force_plot1.png")
type(img)

classif_re2 = classification_report(y_tst2,predics2)
print(classif_re2)

f1score2 = f1_score(y_tst2,predics2, average='weighted')
print(f1score2)

# save the model
joblib.dump(rf, "rta_model_deploy3.joblib", compress=9)

# import all the app dependencies
!pip install streamlit
import streamlit as st
from IPython import get_ipython

# load the encoder and model object
model = joblib.load("rta_model_deploy3.joblib")
encoder = joblib.load("ordinal_encoder2.joblib")

st.set_option('deprecation.showPyplotGlobalUse', False)

# 1: serious injury, 2: Slight injury, 0: Fatal Injury

st.set_page_config(page_title="Accident Severity Prediction App",
                page_icon="🚧", layout="wide")

#creating option list for dropdown menu
options_day = ['Sunday', "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
options_age = ['18-30', '31-50', 'Over 51', 'Unknown', 'Under 18']

# number of vehical involved: range of 1 to 7
# number of casualties: range of 1 to 8
# hour of the day: range of 0 to 23

options_types_collision = ['Vehicle with vehicle collision','Collision with roadside objects',
                           'Collision with pedestrians','Rollover','Collision with animals',
                           'Unknown','Collision with roadside-parked vehicles','Fall from vehicles',
                           'Other','With Train']

options_sex = ['Male','Female','Unknown']

options_education_level = ['Junior high school','Elementary school','High school',
                           'Unknown','Above high school','Writing & reading','Illiterate']

options_services_year = ['Unknown','2-5yrs','Above 10yr','5-10yrs','1-2yr','Below 1yr']

options_acc_area = ['Other', 'Office areas', 'Residential areas', ' Church areas',
       ' Industrial areas', 'School areas', '  Recreational areas',
       ' Outside rural areas', ' Hospital areas', '  Market areas',
       'Rural village areas', 'Unknown', 'Rural village areasOffice areas',
       'Recreational areas']

# features list
features = ['Number_of_vehicles_involved','Number_of_casualties','Hour_of_Day','Type_of_collision','Age_band_of_driver','Sex_of_driver',
       'Educational_level','Service_year_of_vehicle','Day_of_week','Area_accident_occured']

# Give a title to web app using html syntax
st.markdown("<h1 style='text-align: center;'>Accident Severity Prediction App 🚧", unsafe_allow_html=True)

def main():
    with st.form("road_traffic_severity_form"):
        st.subheader("Please enter the following inputs:")
        No_vehicles = st.slider("Number of vehicles involved:",1,7, value=0, format="%d")
        No_casualties = st.slider("Number of casualties:",1,8, value=0, format="%d")
        Hour = st.slider("Hour of the day:", 0, 23, value=0, format="%d")
        collision = st.selectbox("Type of collision:",options=options_types_collision)
        Age_band = st.selectbox("Driver age group?:", options=options_age)
        Sex = st.selectbox("Sex of the driver:", options=options_sex)
        Education = st.selectbox("Education of driver:",options=options_education_level)
        service_vehicle = st.selectbox("Service year of vehicle:", options=options_services_year)
        Day_week = st.selectbox("Day of the week:", options=options_day)
        Accident_area = st.selectbox("Area of accident:", options=options_acc_area)
        
        submit = st.form_submit_button("Predict")
    
    if submit:
        input_array = np.array([collision,
                                Age_band,Sex,Education,service_vehicle,
                                Day_week,Accident_area], ndmin=2)
        
        encoded_arr = list(encoder.transform(input_array).ravel())
        
        num_arr = [No_vehicles,No_casualties,Hour]
        pred_arr = np.array(num_arr + encoded_arr).reshape(1,-1)
    
        prediction = model.predict(pred_arr)
        
        if prediction == 0:
            st.write(f"The severity prediction is Fatal Injury⚠")
        elif prediction == 1:
            st.write(f"The severity prediction is serious injury")
        else:
            st.write(f"The severity prediction is slight injury")
        
        st.subheader("Explainable AI (XAI) to understand predictions")
        shap.initjs()
        shap_values = shap.TreeExplainer(model).shap_values(pred_arr)
        st.write(f"For prediction {prediction}") 
        shap.force_plot(shap.TreeExplainer(model).expected_value[0], shap_values[0],pred_arr, feature_names=features, matplotlib=True,show=False).savefig("pred_force_plot.jpg", bbox_inches='tight')
        img = Image.open("pred_force_plot1.jpg")
        
        st.image(img, caption='Model explanation using shap')
        
        st.write("Developed By: Avi Kumar Talaviya")
        st.markdown("""Reach out to me on
 [Twitter](https://twitter.com/avikumart_) |
              [Linkedin](https://www.linkedin.com/in/avi-kumar-talaviya-739153147/) |
              [Kaggle](https://www.kaggle.com/avikumart)""")

import streamlit as st

def main():
    a,b,c = st.columns([0.2,0.6,0.2])
    with b:
        st.image("/content/car-accident.webp", use_column_width=True)

    st.subheader("🧾Description:")
    st.text("""This data set is collected from Addis Ababa Sub-city police departments for master's research work. 
    The data set was prepared from manual documents of road traffic accidents of the year 2017-20. 
    All the sensitive information has been excluded during data encoding and finally it has 32 features and 12316 instances of the accident.
    Then it is preprocessed and for identification of major causes of the accident by analyzing it using different machine learning classification algorithms.
    """)

    st.markdown("Source of the dataset: [Click Here](https://www.narcis.nl/dataset/RecordID/oai%3Aeasy.dans.knaw.nl%3Aeasy-dataset%3A191591)")

    st.subheader("🧭 Problem Statement:")
    st.text("""The target feature is Accident_severity which is a multi-class variable. 
    The task is to classify this variable based on the other 31 features step-by-step by going through each day's task. 
    The metric for evaluation will be f1-score
    """)

    st.markdown("Please find GitHub repository link of project: [Click Here](https://github.com/avikumart/Road-Traffic-Severity-Classification-Project)")

if __name__ == '__main__':
    main()

